twig:
    file_name_pattern: '*.twig'
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    paths:
            '%kernel.project_dir%/templates': ~

when@test:
    twig:
        strict_variables: true
