messages:
  creer : 'Sortie ajoutée avec succès !'
  modifier: 'Sortie modifiée avec succès !'
  desister:
    noninscrit: 'Vous n''êtes pas inscrit à cette sortie.'
    impossible: 'Vous ne pouvez pas vous désister d''une sortie qui n''est pas ouverte.'
    succes: 'Désistement de la sortie réussi !'
  publier:
    succes: 'Sortie publiée avec succès !'
    impossible: 'Vous ne pouvez pas publier une sortie que vous n''avez pas créée.'
  annuler:
    succes: 'Sortie annulée avec succès !'
    impossible: 'Vous ne pouvez pas annuler une sortie que vous n''avez pas créée.'
  inscrire:
    dejainscrit: 'Vous êtes déjà inscrit à cette sortie.'
    nonouverte: 'Vous ne pouvez pas vous inscrire à une sortie qui n''est pas ouverte.'
    depassee: 'La date limite d''inscription est dépassée.'
    complete: 'La sortie est complète.'
    reussie: 'Inscription à la sortie réussie !'
  lieu :
    ajouter : 'Lieu ajouté avec succès !'
    dejaexistant : 'Un lieu avec ce nom existe déjà.'
  participant :
    nontrouve : "Oups, le profil du participant n'a pas été trouvé !"
    mauvaisprofil : "Vous ne pouvez modifier que votre propre profil."
    succes : 'Le profil a été modifié avec succès.'




