# config/services.yaml
parameters:
    participants_images_directory: '%kernel.project_dir%/assets/images/profile'
    timezone: '%env(APP_TIMEZONE)%'

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    App\Service\MessageService:
        arguments:
            $projectDir: '%kernel.project_dir%'
